### ISSUE TITLE
install missing packages

### ISSUE THREAD

**Issue by B1Sandmann** [killermoehre/tinyipa#11]
timedatectl

**Comment by B1Sandmann** [comment]
awk

**Comment by B1Sandmann** [comment]
cut

**Comment by B1Sandmann** [comment]
rootcertificates are missing

**Comment by B1Sandmann** [comment]
regarding certificates: curl is reporting on trying access a https url:

curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CAPath: none

**Comment by killermoehre** [comment]
Everything installed.
