### ISSUE TITLE
Adjust logging format

### ISSUE THREAD

**Issue by B1Sandmann** [killermoehre/tinyipa#12]
As we're logging to the journal we don't need the timestamp from IPA itself, it's only redundant information that makes the logs harder to read. There is a `use_journal` in oslo.log https://docs.openstack.org/oslo.log/latest/configuration/index.html which IPA is using. Only question on were one would need to configure this. It seems to be part of oslo.config https://docs.openstack.org/oslo.config/latest/

**Comment by killermoehre** [comment]
fixed with https://github.com/killermoehre/fedIPA/commit/f361e1f96e632efa558ce22765a755a52f852407
